name: Deploy to Dev Environment

on:
  push:
    branches:
      - trivy-exit

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy Vulnerability Scan in repo mode
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKER_USER }}
          TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.SUPER_PAT }}
        run: |
          trivy repo \
            --db-repository public.ecr.aws/aquasecurity/trivy-db \
            --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db \
            --scanners vuln,secret \
            --format table \
            --ignore-unfixed \
            --severity CRITICAL,HIGH \
            --output trivy-results-repo.txt \
            https://github.com/Helium-Health/helium-kudos-server || true

          cat trivy-results-repo.txt
          if grep -qE 'CRITICAL|HIGH' trivy-results-repo.txt; then
            echo "❌ High or Critical vulnerabilities found in repo scan — failing job."
            exit 1
          fi

      - name: Build and push Docker image
        run: |
          docker build -t 1med/helium-kudos-server-dev .
          docker push 1med/helium-kudos-server-dev

      - name: Run Trivy Vulnerability Scan on Docker image
        env:
          TRIVY_USERNAME: ${{ secrets.DOCKER_USER }}
          TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          trivy image \
            --db-repository public.ecr.aws/aquasecurity/trivy-db \
            --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db \
            --scanners vuln \
            --ignore-unfixed \
            --severity CRITICAL,HIGH \
            --format table \
            --output trivy-results-image.txt \
            1med/helium-kudos-server-dev || true

          cat trivy-results-image.txt
          if grep -qE 'CRITICAL|HIGH' trivy-results-image.txt; then
            echo "❌ High or Critical vulnerabilities found in Docker image — failing job."
            exit 1
          fi

      - name: Upload Trivy scan results to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: |
            trivy-results-repo.txt
            trivy-results-image.txt
