name: Deploy to Staging Environment

on:
  push:
    branches:
      - staging
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'repo'
          hide-progress: false
          format: 'table'
          output: "trivy-results-repo.txt"
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'    

      - name: Run Trivy Vulnerability Scan
        env:
         TRIVY_USERNAME: ${{ secrets.DOCKER_USER }}
         TRIVY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
         trivy image \
            --db-repository public.ecr.aws/aquasecurity/trivy-db \
            --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db \
            --scanners vuln \
            --output trivy-results-image.txt \
            onemed/helium-kudos-server-staging:latest
          

      - name: Set up ArgoCD CLI
        run: |
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd

      - name: ArgoCD Login
        run: |
          yes | argocd login ${{ vars.ARGOCD_STAGING_URL }} --insecure --username ${{ secrets.ARGOCD_USERNAME }} --password  ${{ secrets.ARGOCD_PASSWORD }}

      - name: ArgoCD Sync App
        env:
          APP_NAME: helium-kudos-server-staging
        run: |
          argocd app actions run $APP_NAME restart --kind Deployment --resource-name helium-kudos-server-staging --all
          
